default_printer: ender3_pro
printers:
  ender3_pro:
    name: Ender 3 Pro
    bed_size_mm:
      width: 210.0
      depth: 210.0
    origin_offsets_mm:
      x_min: 10.0
      x_max: 210.0
      y_min: 10.0
      y_max: 210.0
    z_heights_mm:
      draw: 0.0
      travel: 1.5
    z_lift_height_mm: 1.5
    feedrates_mm_s:
      draw: 175.0
      travel: 175.0
      z: 20.0
    color_mode: true
    available_colors:
      - "#000000" # Black
      - "#9d5352" # Red
      - "#c7663e" # Orange
      - "#baa961" # Yellow
      - "#87bd5c" # Lime
      - "#4bbd5d" # Green
      - "#328f68" # Turqoise
      - "#4dd1c1" # Cyan
      - "#292f7d" # Blue
      - "#69409c" # Purple
      - "#bf4e95" # Pink
    pause_gcode:
      - "G91 ; relative positioning"
      - "G1 Z20 F600 ; lift pen safely"
      - "G90 ; absolute positioning"
      - "G1 X0.000 Y0.000 F10500 ; move to park for swap"
      - "M0 Change pen and press to resume"
    start_gcode:
      - G21 ; use millimeters
      - G90 ; absolute positioning
      - G28 ; home all axes
      - G1 Z2.0 F10500 ; lift pen to travel height
      - G1 X14.000 Y14.000 F10500 ; move to front-left start
    end_gcode:
      - G1 Z2.0.000 F10500 ; lift pen
      - G1 X14.000 Y206.000 F10500 ; park at rear-left
      - M18 ; disable steppers
  prusa_xl:
    name: Prusa XL
    bed_size_mm:
      width: 360.0
      depth: 360.0
    origin_offsets_mm:
      x_min: 1.0
      x_max: 208.0
      y_min: 72.0
      y_max: 290.0
    z_heights_mm:
      draw: 2.5
      travel: 4.5
    z_lift_height_mm: 2.0
    feedrates_mm_s:
      draw: 400.0
      travel: 400.0
      z: 40.0
    color_mode: false
    available_colors:
      - "#000000"
    pause_gcode:
      - "M600"
    start_gcode:
      - G21 ; use millimeters
      - G90 ; absolute positioning
      - G28 ; home all axes
      - G1 Z4.500 F10500 ; lift pen to travel height
      - P0 S1 ; Park XL Head
      - G1 X1.000 Y70.000 F10500 ; move to front-left start
    end_gcode:
      - G1 Z39.000 F10500 ; lift pen
      - G1 X0.000 Y350.000 F10500 ; park at rear-left
      - M18 ; disable steppers
infill:
  base_line_spacing_mm: 1.0
  min_density: 0.0
  max_density: 1.0
  angles_degrees: [45, -45]
perimeter:
  thickness_mm: 0.45
  density: 1.0
  min_fill_width_mm: 0.8
sampling:
  segment_length_tolerance_mm: 0.4
  outline_simplify_tolerance_mm: 0.4
  curve_detail_scale: 3.0
rendering:
  preview_line_width_mm: 0.45
